### ISSUE TITLE
MS:1002404 (count of identified proteins) ought to be a child of MS:1001184 (search statistics)?

### ISSUE THREAD

**Issue by hbarsnes** [HUPO-PSI/mzIdentML#8]
MS:1002404 (count of identified proteins) is _not_ a child of MS:1001184 (search statistics)? Should it not be? Will remove warning messages when running the validator.

**Comment by germa** [comment]
Done in version 3.86.0 of psi-ms.obo

**Comment by hbarsnes** [comment]
Seems like the ProteinDetectionList_rule does not allow children of MS:1001184 (search statistics) only children of MS:1002406 (count of identified clusters)? Shouldn't children of MS:1001184 (search statistics) also be allowed?

Complete validator message:

```
Rule ID: ProteinDetectionList_rule
    Level: INFO
    Context(/cvParam/@accession ) in 2 locations
    --> Not all of the 1 values ProteinDetectionList's CV terms ['MS:1002404'] found using the Xpath '/cvParam/@accession' matched any of the 2 CvTerm(s):
  - Any children term of MS:1001184 (search statistics). The term can be repeated. The matching value has to be the identifier of the term, not its name.
  - The sole term MS:1002406 (count of identified clusters) or any of its children. A single instance of this term can be specified. The matching value has to be the identifier of the term, not its name.
```

**Comment by andrewrobertjones** [comment]
Seems to be solved, closing. Can be re-opened if issue still exists

**Comment by hbarsnes** [comment]
I still get the same info message when running the current validator on the PeptideShaker mzid 1.2 example file: https://github.com/HUPO-PSI/mzIdentML/blob/master/examples/1_2examples/PeptideShaker_mzid_1_2_example/PeptideShaker_mzid_1_2_example.mzid.gz.

**Comment by germa** [comment]
Solved now.
